# Generated by Django 4.0.4 on 2022-05-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disdate', models.DateField(auto_created=True)),
                ('admitdate', models.DateField(auto_created=True)),
                ('pname', models.CharField(max_length=20)),
                ('mailid', models.EmailField(max_length=254)),
            ],
        ),
    ]
