# Generated by Django 4.0.4 on 2022-06-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_dob', models.DateField(auto_created=True)),
                ('E_id', models.IntegerField()),
                ('E_name', models.CharField(max_length=20)),
                ('E_city', models.CharField(max_length=20)),
                ('E_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
