# Generated by Django 4.0.4 on 2022-05-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classicbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpublisheddate', models.DateField(auto_created=True)),
                ('bname', models.CharField(max_length=20)),
                ('bqnty', models.IntegerField()),
                ('bauthor', models.CharField(max_length=20)),
                ('bprice', models.IntegerField()),
                ('bpublication', models.CharField(max_length=25)),
            ],
        ),
    ]
